### ISSUE TITLE
xml output: extra labels added

### ISSUE THREAD

**Issue by timmli** [xmg-hhu/xtag2xml#2]
Sometimes an extra label is attached to a feature structure that also appears inside the feature structure, for example `@M` in the following snippet from `betaVs.xml`:

> ```
>            <node name="V" type="anchor">
>                 <narg>
>                     <fs coref="@M">
>                         <f name="top">
>                             <fs coref="@M">
> ```

Interestingely enough, `@M` does not appear in the corresponding JSON:

> ```
>            "name": "V#headp",
>             "children": [],
>             "features": {
>                 "t": {
>                     "<assign-case>": "@I",
>                     "<agr>": "@G",
>                     "<mode>": "ind",
>                     "<neg>": "@H",
>                     "<tense>": "@F"
>                 },
>                 "b": {
>                     "<agr>": "@A"
>                 }
>             }
> ```

My guess is that these extra labels are inserted during the conversion from JSON to XML.

**Comment by timmli** [comment]
Are you sure this fixed the bug? I'm still getting the extra labels (now `@L` though).

> ```
>             <node name="V" type="anchor">
>                 <narg>
>                     <fs coref="@L">
>                         <f name="top">
>                             <fs coref="@L">
>                                 <f name="agr">
>                                     <sym varname="@G"/>
>                                 </f>
> ```

**Comment by eseyffarth** [comment]
It turned out there was a problem in the JSON part as well as in the XML part. Both should be fixed now!
