### ISSUE TITLE
README.md: Python version

### ISSUE THREAD

**Issue by timmli** [xmg-hhu/xtag2xml#4]
> Written in Python 3.4.

Shouldn't it be Python 3.5? I cannot compile under cygwin which only has Python 3.4.

**Comment by eseyffarth** [comment]
Which problems exactly do you get? It works on my machine under Python 3.4.3
Is there a problem with the package requirements?

**Comment by timmli** [comment]
Ok, now it also works with Python 3.4 under Cygwin. The problem was related to pip, which has to be installed with extra scripts, not via the Cygwin setup tool. Anyway, thanks!
